### ISSUE TITLE
[BUG] Default toolbar is shown even when buttons are specified

### ISSUE THREAD

**Issue by tneotia** [tneotia/html-editor-enhanced#13]
**Describe the bug**
> Another issue is sometimes it shows the default toolbar even if you specified which buttons I want to show

From @blue492

**Comment by blue492** [comment]
My code is here in this link [https://github.com/tneotia/html-editor-enhanced/issues/11](https://github.com/tneotia/html-editor-enhanced/issues/11)

When I open the page which has html-editor-enhanced widget.
Sometimes it shows the default toolbar even if you specified which buttons I want to show.

I dont know what is the reason because I dont change any thing, it is same code.
In Terminal it shows this error message:
`E/chromium(29339): [ERROR:aw_browser_terminator.cc(125)] Renderer process (5217) crash detected (code -1).
`

**Comment by tneotia** [comment]
Yep I am able to reproduce it consistently. Let me investigate.

**Comment by tneotia** [comment]
Fixed in the above commit. jQuery's `document.onReady()` was interfering with the correct initialization somehow. Thanks for reporting!

**Comment by blue492** [comment]
> Fixed in the above commit. jQuery's `document.onReady()` was interfering with the correct initialization somehow. Thanks for reporting!

Perfect, should I do Pub get now or waiting for a new version?

**Comment by tneotia** [comment]
I probably won't release another version to Pub since I just did an hour ago, if you want to try immediately, you can replace `html_editor_enhanced: ^1.7.0+1` with 

```yaml
html_editor_enhanced:
   git:
      url: https://github.com/tneotia/html-editor-enhanced.git
      ref: master
```

**Comment by blue492** [comment]
Thanks, I want to add 'ol', 'ul', 'link' and 'image' to the toolbar, how to do it?
 
```
toolbar: [
             Style(),
              Font(buttons: [FontButtons.bold,  FontButtons.italic, FontButtons.clear, FontButtons.underline],),
            ],
```

**Comment by tneotia** [comment]
They are under separate constructors. You would do this:

```dart
toolbar: [
             Style(),
             Font(buttons: [FontButtons.bold,  FontButtons.italic, FontButtons.clear, FontButtons.underline],),
             Paragraph(buttons: [ParagraphButtons.ol, ParagraphButtons.ul]),
             Insert(buttons: [InsertButtons.link, InsertButtons.picture]),
],
```

See `utils > toolbar.dart` for all the constructors.

**Comment by blue492** [comment]
Thanks for all help, keep calm
