### ISSUE TITLE
[QUESTION]How to hide toolbar and resize line in the bottom?

### ISSUE THREAD

**Issue by akmichael** [tneotia/html-editor-enhanced#136]
Hi,
How to hide the toolbar and resize line in the bottom?

    HtmlEditor(
                    controller: htmlController, //required
                    htmlEditorOptions: HtmlEditorOptions(
                      initialText: specUpdate.description,
                    ),
                    otherOptions: OtherOptions(
                      height: 180,
                    ),
                    htmlToolbarOptions:
                        HtmlToolbarOptions(defaultToolbarButtons: [
                      ParagraphButtons(lineHeight: false, caseConverter: false)
                    ]))

![html text](https://user-images.githubusercontent.com/8349884/133085299-e48aa127-8135-4c2b-8810-078a07de42ab.png)

**Comment by tneotia** [comment]
Hi, to hide toolbar you can set `toolbarPosition: ToolbarPosition.custom` and then just put a `ToolbarWidget` randomly in your code with `Visibility(visible: false, child: ...)` so it is hidden. Currently I have no functionality to "officially" hide toolbar but this is a workaround you can use. `ToolbarWidget` is required otherwise the editor may throw exceptions because it cannot find the toolbar.
To resize line, there is no API. You can remove it if you want with `controller.setFullscreen()`, call this in `onInit` callback to remove it when the editor starts automatically.
