### ISSUE TITLE
[QUESTION] Custom Toolbar for Increase or Decrease font size

### ISSUE THREAD

**Issue by lucasdidur** [tneotia/html-editor-enhanced#139]
Hello, 

I Want create 2 buttons that one is for increase the font size of a selected text and another for decrease. 
Its possible to create like this?

**Comment by tneotia** [comment]
Yes you can create it with `customToolbarButtons`. Just provide your widget and then you can see the code here: https://github.com/tneotia/html-editor-enhanced/blob/master/lib/src/widgets/toolbar_widget.dart#L810 that I use to change the fontSize via JavaScript. If you have any questions or would like a basic example let me know, and sorry for the late response!

**Comment by frk0708** [comment]
Hello @tneotia,
Actually, I want to add more font Sizes in editor.As you mentioned in previous comment.I created a dropdown widget with needed font sizes and added the following code in onChange function.
controller.execCommand('fontSize',
                          argument: changed.toString());
but,the selected text reflected with some default size instead of choosen value.What to do?
