### ISSUE TITLE
[FEATURE] HtmlEditorOptions styling

### ISSUE THREAD

**Issue by rgr** [tneotia/html-editor-enhanced#150]
**Is your feature request related to a problem? Please describe.**
I would like to be able to style the text area as I am currently able to style the toolbar : cursor color, area background color, area radius, etc.

**Describe the solution you'd like**
Same syling options as the toolbar with the possibility to edit the rendering of text (h1, h2, etc.)

**Comment by tneotia** [comment]
To edit the rendering of text and such I recommend you create a CSS file that affects text rendering and inject it into the webview. There is no good way to allow styling options for the text within Dart since it is rendered in HTML, which is why CSS is the best way to go. This will ensure that your custom style affects all text for any font type, color, size, etc.

**Comment by rgr** [comment]
Ok thanks. Maybe I missed it but I didn't see any doc about the available classes to style. How would I go rounding the corners of the text field ? Classic text area css styling ? A short example in the doc would be awesome :)

**Comment by tneotia** [comment]
> So i got it to work but I still get the caret decoration in that color. Any idea of it's class to change the color ?

The selection handle is controlled by Android theming. You can check https://github.com/tneotia/html-editor-enhanced/issues/138 for how to change its color.

**Comment by tneotia** [comment]
Hopefully these answers helped you, closing this issue for now. Let me know if you have other questions!
