### ISSUE TITLE
Scrolling issue while Editor inside the ScrollView

### ISSUE THREAD

**Issue by pratik-7span** [tneotia/html-editor-enhanced#158]
How do I Scroll whole page If **HtmlEditor** is inside of **SingleChildScrollView.**

I can scroll page until the HTML Editor options, after that I can't scroll the page to bottom. I can't scroll up/down after hovering on HTML Editor and If I move cursor outside of HTML Editor then its working. 

Note: I have used [`shouldEnsureVisible: true`](https://pub.dev/packages/html_editor_enhanced#shouldensurevisible) to scroll editor at top.

Can anyone face this problem? Can anyone help me out?

**Comment by tneotia** [comment]
Unfortunately this is a problem with Flutter, there is no way to work around it. The webview region acts like a separate page and absorbs all the scroll events. If you want to use the editor in a scrolling form, the best way would be to add a button to open the editor, allow the user to type, and then go back to the main form once they are done.

**Comment by Fauzdar1** [comment]
Issues like these persist in every such editor available on pub.dev. And, as what happens very often in Flutter development, there's no possible way to tackle that. In flutter web, Scrolling using mouse wheel stops working when the cursor is above the Editor. 

Only workaround is to use a visible ScrollBar so that the user can scroll the page using it.

**Comment by zhengxiangke** [comment]
how to solve this

**Comment by Fauzdar1** [comment]
> how to solve this

You can't actually. I remember trying to customise the inherent scroll behaviour but nothing had worked. The workaround was to Show a similar styled Text box instead of the HTML editor, and when the user clicks on it to type, a popup is opened with the editor. Hence, the main layout never consists the HTML editor making it properly scrollable, editing was breeze too in the full-screen popup. Worked like a charm.

**Comment by hybridkiplteam** [comment]
@tneotia @pratik-7span @Fauzdar1 @zhengxiangke 

I am also facing this issue I can scroll page until the HTML Editor options, after that I can't scroll the page to bottom. I can't scroll up/down after hovering on HTML Editor.

Has anyone found a solution or an alternative way to do this?
