### ISSUE TITLE
[BUG] Tooltip overlays the pop-up box

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#163]
![image](https://user-images.githubusercontent.com/42678103/142177142-cf472c1e-531f-49d9-a119-5924999003cc.png)
When I long press some content, then click the color button, and the Tooltip **overlays** the pop-up box.
Is there any solution can solve this problem?

**Comment by SheepYang1993** [comment]
I have the same problem

**Comment by tneotia** [comment]
This is yet another issue with Flutter webview / platform view support. It seems that platform view overlay rendering takes priority over the Flutter overlay rendering, which is why the tooltip shows on top of the alert dialog. Unfortunately I cannot do anything about this, Flutter will have to fix this issue :(
