### ISSUE TITLE
FormatException: Invalid character (at character 5)

### ISSUE THREAD

**Issue by indjec** [tneotia/html-editor-enhanced#18]
flutter: FormatException: Invalid character (at character 5)
data:image/jpeg;base64,/9j/4Sq1RXhp....

Error while gettting image onImageUpload

**Comment by tneotia** [comment]
Can you provide your code in onImageUpload so I can determine where the error is happening? Thanks

**Comment by indjec** [comment]
onImageUpload: (FileUpload file) async {
        Uint8List list = base64.decode(file.base64);

      controller.uploadImageFirst(list);
      },

Actually my server accepts parameter of type File to upload the image first, when onImageUpload is selected it throws the exception

My code does not hits the api to upload

flutter: FormatException: Invalid character (at character 5)
data:image/jpeg;base64,/9j/4Sq1RXhp....

**Comment by indjec** [comment]
If you could add the file path all the errors will be solved

**Comment by tneotia** [comment]
> flutter: FormatException: Invalid character (at character 5)
> data:image/jpeg;base64,/9j/4Sq1RXhp....

This issue is from the code `Uint8List list = base64.decode(file.base64);`, you need to do `file.base64.split(",")[1]` I think. This strips out the initial identifying data (`data:image/jpeg;base64,`) which causes the exception. Please let me know if this solves the issue so I can update it in the README.

> is it possible to upload frombytes when my server accepts parameter of type File
> 
> Adding the path would solve many problems.

Unfortunately I cannot add path as the browser has no idea of the path when getting the file. This is due to security reasons and is the case for all browsers on any platform. I also have no way to intercept the file picker to get the file path, again for security reasons.

Thus, when the browser uploads a file it uses `fromBytes`, so your server should be just fine in accepting data from bytes.
