### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by tanzilzubair** [tneotia/html-editor-enhanced#187]
Firstly I'd just like to say awesome awesome work with this project man. You've put a trememdous amount of work into this and it really shows.

So now, moving on to my question, is there a way to implement a find function into the editor? So that, for examle, a user clicks on a find icon, enters some text, and the document is searched for that text, and if it is found, the cursor is programmatically moved to that place? 

If its already implemented and I haven't found it, then that's great, but if its not, could you please help me out and implement this feature? It would be useful to a lot of people, including me, and be a really cool feature for the editor. Thanks in advance, and again, great job with this package!

**Comment by tneotia** [comment]
Hi, this might be a bit overkill to implement into the project itself, but at least on mobile you can do this fairly easily:

1. You will want to create a custom button with the find icon inside the toolbar (see [here](https://github.com/tneotia/html-editor-enhanced#customtoolbarbuttons-and-customtoolbarbuttonsinsertionindices) for details on how to do this)

2. Use the `InAppWebViewController` [findNext](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewController/findNext.html) method inside the `onPressed` of your button, using `htmlController.editorController.findNext`, and that will move the cursor programatically.

If you are trying to do it on Web, it might just be easiest to make the user use the Ctrl-F dialog rather than making your own implementation.
