### ISSUE TITLE
Editor scale [QUESTION]

### ISSUE THREAD

**Issue by coccyx-cyst** [tneotia/html-editor-enhanced#199]
Can I somehow scale editor's height to the size of screen?

**Comment by coccyx-cyst** [comment]
also I'm trying to use jsScript for Html editor to control size of images and iframe videos, but no changes appears.

Like so """
            meta.name = 'viewport';
            meta.content = 'width=device-width';
            var style = document.createElement('style');
            style.innerHTML = `
                img{display: inline;height: auto;max-width: 100%;}
                iframe{
                    border-radius: 8px; 
                    max-width: 100%; max-height: 220px; 
                    display: block; margin-left: auto;
                    margin-right: auto;}`
            var head = document.getElementsByTagName('head')[0];
            head.appendChild(meta);
            head.appendChild(style);"""
 Is it possible to do something like this with that editor?

**Comment by tneotia** [comment]
For the first question, yes, use the `height` parameter inside `otherOptions` to set the height. You will have to do some calculation with MediaQuery and appBarHeight if you have an app bar.

As for second question - I don't know if that will work because Summernote itself has custom methods for changing the size of the images. I would suggest trying to use `mediaUploadInterceptor` and manually adding the width inside each `img` tag before it is inserted into the editor.

**Comment by coccyx-cyst** [comment]
@tneotia got it.

One more question if you will.
I am using Scaffold Drawer in my app, and I noticed that when I am at the page which using editor the Drawer begins losing fps. Did you notice such a behavior? This is especially noticable on Android.

**Comment by tneotia** [comment]
This is likely due to the webview being a platform view. Flutter does not play nice with them, and oftentimes animations will begin to look very weird when playing on top of the platform view, this has been the case for a long time.

I may add a parameter to allow disabling the `Hybrid Composition` method of rendering the webview at the cost of worse keyboard support, for those who want to maintain the animation quality.

**Comment by coccyx-cyst** [comment]
@tneotia tnx a lot
