### ISSUE TITLE
How do we get the Image button in the bottomtoolbar? Thanks

### ISSUE THREAD

**Issue by indjec** [tneotia/html-editor-enhanced#20]

**Comment by tneotia** [comment]
I removed it since it was working from the Summernote button. I assume you want this to handle image uploads easier.

If you want this back you can just set `showBottomToolbar: false` and make your own - it isn't super hard.

The code for the toolbar widget is all [here](https://github.com/tneotia/html-editor-enhanced/blob/master/lib/utils/toolbar_widget.dart), simply wrap the HtmlEditor and this widget you make in a Column:

```dart
Column(
   children: [
      HtmlEditor()
      Toolbar()
   ]
)
```
You may need to constrain the column with a container? I don't know for sure. Also `shrinkWrap` and `mainAxisSize` might be helpful.

**Comment by tneotia** [comment]
Closing this for now, hopefully the above comment was helpful.
