### ISSUE TITLE
[BUG] Link modal opening in webview and not native

### ISSUE THREAD

**Issue by salihagic** [tneotia/html-editor-enhanced#228]
Dialog that is shown when clicking the button for inserting a link is shown as a flutter dialog but once we add the link and try to edit it by clicking on the newly generated link in the editor we are presented with a bootstrap modal inside the editor.

**Steps to reproduce the behavior**
1. Click on insert link option in editor's toolbar
2. Add text and URL (eg. Google and www.google.com) and click OK
3. Click on the newly generated link in the editor
4. From the tooltip that is showing a URL and some options choose the option to edit the link
5. The modal is shown

**Expected behavior**
The modal for editing the link should be the same as the one for inserting the link (eg. flutter dialog and not bootstrap modal).

**Screenshots**
![image](https://user-images.githubusercontent.com/24563963/155985383-5a08acfe-0262-41f4-acee-0f127cb06a86.png)

**Device:**
Tested this on android

**Comment by tneotia** [comment]
Unfortunately this is not a bug, due to using a webview, I can't detect the click on the link and override it to show the flutter dialog instead. If you don't like the UX, you can completely disable the bootstrap link modal by following https://github.com/tneotia/html-editor-enhanced/issues/123#issuecomment-971088834
