### ISSUE TITLE
[QUESTION] implementing save body html alwasy auto input <br> tags

### ISSUE THREAD

**Issue by weebsproject** [tneotia/html-editor-enhanced#232]
Type question here.
hello ,

when i saved my html body and then i log 
it show like that

```
</p><p>one sheep one goals</p><p>excelente !</p>
```

then when i init above html text into on init.

it shows

```
<p><br></p><p>one sheep one goals</p><p>excelente !</p>
```

how can i remove annoying <p><br> while i input the body on the onInit?

**Comment by tneotia** [comment]
This is there because of Summernote, nothing we can do. I suggest just checking the front of the string for the `<p></br></p>` and removing it if it is there, before you upload or save the HTML.

**Comment by IKRAMULHAQ786** [comment]
I have a similar question.
I used this package hoping that it will give me the text in html format. So that I can save it to server, and on retrieving the HTML will be displayed on the screen.
but it gives the text that statrs wth <p> tags, which is not the proper html text.
what should I do to resolve issue

**Comment by IKRAMULHAQ786** [comment]
I mean I will upload html containing some bulleted list, some normal text, some headings.
And when that is retrieved , I want to show the exact html that i saved.
how can I do that.
