### ISSUE TITLE
[BUG]click the editor then cursor is at second line

### ISSUE THREAD

**Issue by sweatfryash** [tneotia/html-editor-enhanced#24]
**Describe the bug**
click editor then cursor is at second line

**To Reproduce**
build it like my code(in Additional context) and click the editor

**Expected behavior**
click editor then cursor is at first line

**Screenshots**
![](https://ftp.bmp.ovh/imgs/2021/04/12eaa78df4f5573f.gif)

**Device:**
android 9,real

**Additional context**
```
Expanded(
            child: HtmlEditor(
              controller: controller, //required
              hint: "Your text here...",
              options: HtmlEditorOptions(
                height: 400,
              ),
            ),
          )
```

**Comment by sweatfryash** [comment]
I think I found the reason:after focused the code is <p><br/></p> so it looks like at second line.But the problem is the 'hint' is at first line,it`s abnormal.

**Comment by tneotia** [comment]
Hi there, thanks for your report. Unfortunately this is just how Summernote editor functions and I cannot change that. You can see [here on the official website](https://summernote.org/getting-started/#without-bootstrap) the same behavior is there.

The reason for this is because by default the text in the editor is `<p><br/></p>` which makes the cursor at the second line - this is necessary for this reason:

> The editing area needs `<p><br></p>` for focus, even if the editor content is empty. 

As seen [here](https://summernote.org/deep-dive/#isempty).

**Comment by sweatfryash** [comment]
thanks for reply, I will try to find some way to resolve.: )

**Comment by tneotia** [comment]
Maybe in your hint add new line or br:

`\nYour text here...`

or

`<br/>Your text here...`

I don't know which one will work but one of them should.

**Comment by sweatfryash** [comment]
I found use \<p>hinttext\<p/> is very nice, use\<br/> causes different line height.

**Comment by tneotia** [comment]
Great, thanks for posting your solution!

**Comment by lanwufeng** [comment]
I found that   **initialText:''**    is also possible
