### ISSUE TITLE
[BUG] toolbar option buttons should be visible for any frame size

### ISSUE THREAD

**Issue by anamak9** [tneotia/html-editor-enhanced#33]
**Describe the bug**
defaultToolbarButtons not visible for all types.

**To Reproduce**
See screenshot below

**Expected behavior**
All toolbar options should be fitted for any dimensions available

**Screenshots**
![toolbar-issue](https://user-images.githubusercontent.com/83526432/116824828-44867180-ab5a-11eb-9554-7473befda826.JPG)

**Device:**
Android emulator

**Additional context**
Version:
html_editor_enhanced: ^2.0.1

I think it used work fine in two versions prior this one.

**Comment by tneotia** [comment]
Hi there, please use `toolbarType: ToolbarType.nativeGrid` to be able to see all the buttons visible (like previous versions):

```dart
Html(
   //other options
   htmlToolbarOptions: HtmlToolbarOptions(
      //other options
      toolbarType: ToolbarType.nativeGrid,
   )
),
```

**Comment by anamak9** [comment]
Yes that worked but it would be nice to have all options collapsible wherever possible.

![toolbar-fixed](https://user-images.githubusercontent.com/83526432/117210740-173dfb80-adc6-11eb-92ad-6bf7d6da86ce.JPG)

btw what is that divider kind of thing (inside the red circle) ? how do we tweak it for its size etc?

**Comment by tneotia** [comment]
It is just there because it is part of the Summernote editor (see https://summernote.org/ shows the same divider). If you want it to disappear, set the editor "fullscreen" with `<controller>.setFullscreen()` in the `onInit` callback. (see #4 for more details).

> Yes that worked but it would be nice to have all options collapsible wherever possible.

I don't know how this would work but I'll consider it as a feature request. Please make a feature request issue with some more details and I'll look into it :)

Closing this issue as it is resolved.

**Comment by tneotia** [comment]
@anamak9 here's what I came up with for expandable/collapsible options:

https://user-images.githubusercontent.com/50850142/121825585-4aa35e00-cc81-11eb-9e4a-e592a0cd87f0.mp4

What do you think?
