### ISSUE TITLE
Please update the dependencies used in this package

### ISSUE THREAD

**Issue by stashtechnologies** [tneotia/html-editor-enhanced#371]
please update the sub-dependencies as it is conflicting with firebase packages.

**Comment by hayatbangash55** [comment]
yes, this is right... it should be updated immediately.

**Comment by mohsinnaqvi606** [comment]
it have conflict with  **flutter_local_notifications: ^13.0.0**

Here is my error

Because flutter_local_notifications >=13.0.0 depends on flutter_local_notifications_linux ^3.0.0 which depends on ffi ^2.0.1, flutter_local_notifications >=13.0.0 requires ffi ^2.0.1.
And because file_picker ^4.0.0 depends on ffi ^1.1.2, flutter_local_notifications >=13.0.0 is incompatible with file_picker ^4.0.0.
And because html_editor_enhanced 2.5.0 depends on file_picker ^4.6.0 and no versions of html_editor_enhanced match >2.5.0 <3.0.0, flutter_local_notifications >=13.0.0 is incompatible with html_editor_enhanced ^2.5.0.
So, because dealersgear_crm depends on both html_editor_enhanced ^2.5.0 and flutter_local_notifications ^13.0.0, version solving failed.
pub get failed (1; So, because dealersgear_crm depends on both html_editor_enhanced ^2.5.0 and flutter_local_notifications ^13.0.0, version solving failed.)

**Comment by TheCarpetMerchant** [comment]
In case some people are not aware, you can use this :
```yaml
  html_editor_enhanced: #2.5.0
    git:
      url: https://github.com/tneotia/html-editor-enhanced
      #ref: commit
```
in your pubspec. You can use `ref` to specify a commit so that you don't get surprised when something is pushed to `master`.

**Comment by blue492** [comment]
file_picker dependency should also be updated

**Comment by programmermager** [comment]
I forked and already update all packages into latest version. you can use 

`html_editor_enhanced:
    git:
      url: https://github.com/programmermager/html-editor-enhanced.git
      ref: chore/update-packages`
      
in your pubspec.yaml. I already create [PR](https://github.com/tneotia/html-editor-enhanced/pull/373) to for this changes

**Comment by Rishab-ms** [comment]
@programmermager heyy, this is merged into the package itself right?

**Comment by programmermager** [comment]
> @programmermager heyy, this is merged into the package itself right?

hey @Rishab-ms you can ignore my recommendation above. because the MR not merged by @tneotia i think

**Comment by tneotia** [comment]
New version uploaded, sorry for the wait guys
