### ISSUE TITLE
[QUESTION] event imageDelete

### ISSUE THREAD

**Issue by andeersonluiz** [tneotia/html-editor-enhanced#43]
Hello, i would like to know if the widget HtmlEditor has the limageDelete event.

**Comment by tneotia** [comment]
It doesn't have this because Summernote does not have this in the Javascript. However maybe if you use the `onBeforeCommand` & `onChange` callback and the [diff function](https://pub.dev/documentation/diff_match_patch/latest/diff_match_patch/diff.html) you can get the same thing?

Basically compare the text before the change and after the change, if the difference has an `<img>` tag inside then you know an image has been added or deleted, then just check which string had your `<img>` tag. If the text before had it, then you know it was deleted.

Like this:

```dart
String before;

HtmlEditor(
   callbacks: Callbacks(
      onBeforeCommand: (String beforeCommand) => before = beforeCommand,
      onChange: (String changed) {
            //check diff here using the changed and before variables and perform actions
      }
   )
)
```

Don't know for sure if it will work but you can try it, I haven't tested it.
