### ISSUE TITLE
[FEATURE]<Font color> and <Font size> incompatible with Flutter_html package

### ISSUE THREAD

**Issue by andoutica** [tneotia/html-editor-enhanced#46]
Hi guys, 
You made a beautiful package, I love this so much cause I can edit my html by flutter on my devices. 
But I got a issue recently, when I export my html and read it by another package (flutter_html), the font element doesn't support cause they just support html5 . I have to change it to span element with style color and font-size to work normally. 
I don't know if you have a function to export to html5 to support this case.

**Comment by tneotia** [comment]
Hi, thanks for your kind words, glad you like the package!

Unfortunately I can't change it to html5, since I use the `document.execCommand` Javascript which is deprecated. Unfortunately there is still no real replacement for that so most developers still use that deprecated API. When changing font color and font size it uses the older tag.

There is a feature request for `<font>` support in flutter_html linked above, I made my case there to add support for the tag, hopefully the maintainers agree.

**Comment by tneotia** [comment]
PR created at https://github.com/Sub6Resources/flutter_html/pull/694
