### ISSUE TITLE
When will you upgrade package and dependencies?

### ISSUE THREAD

**Issue by gorkemsari** [tneotia/html-editor-enhanced#466]
Upgrade needed for dependent packs. Thank you.

**Comment by nuno84** [comment]
Same here:
Would be great to update the flutter_inappwebview for ^6.0.0-beta.22

Because flutter_super_html_viewer >=0.1.0 depends on flutter_inappwebview ^6.0.0-beta.22 and html_editor_enhanced 2.5.1 depends on flutter_inappwebview ^5.7.2+3, flutter_super_html_viewer >=0.1.0 is incompatible with html_editor_enhanced 2.5.1.

Thank you

**Comment by siunus** [comment]
Same here

`Because html_editor_enhanced >=2.5.1 depends on file_picker ^5.2.0+1 and myapp depends on file_picker ^6.1.1, html_editor_enhanced >=2.5.1 is forbidden.`

**Comment by tneotia** [comment]
New version uploaded, sorry for the wait guys
