### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by raghavan-mookiah** [tneotia/html-editor-enhanced#7]
**Describe the bug**
Not accepting any key inputs in the ios version with the latest flutter version. please check on this. Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device:**
Add device details here.

**Additional context**

**Comment by tneotia** [comment]
Hi, I don't have a physical iOS device but after testing on the Simulator I cannot reproduce this - input is working just fine.

Are you on a physical device? Also your widget code would be helpful to troubleshoot.

**Comment by raghavan-mookiah** [comment]
Hi, The issue on the iOS simulator (iPhone plus 8 - 14.2) only.  
It is a brand new project created using the command flutter create <project-name>
and copied the main file with your example project's main file.

Flutter version is Channel stable, 2.0.3,

pubspec.yaml (below)

name: html_editor_new
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html_editor_enhanced: ^1.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true

**Comment by tneotia** [comment]
Hi, I use iPhone 12 Pro (iOS 14.1) simulator. One thing with the simulator is that it seems the hardware keyboard input doesn't work with the webview for some reason. I have other projects using the same webview plugin and hardware input doesn't work there either.

Because of this, can you try using the software keyboard (do I/O > Keyboard > Toggle Software Keyboard), and use your mouse to click the keys? I do this and it works, which means on a physical iOS device it will work as well.

**Comment by raghavan-mookiah** [comment]
Thanks for your support, closing this bug.
