### ISSUE TITLE
[QUESTION] How to get current cursor in text editor

### ISSUE THREAD

**Issue by Barry0501** [tneotia/html-editor-enhanced#75]
Hi author, I wanna implement the mention user feature in my app. But I don't know how to get the current cursor in a text editor to append user's name after "@". Please give me your opinion

**Comment by tneotia** [comment]
I didn't really understand your question... I have support for showing a list of names for mentions when the user types "@" sign. You don't need to get the current cursor because it will show a list and the user selects the name, and then it automatically appends the name after the "@" sign. If this is not your question can you try to explain a different way so I can answer? :)

**Comment by Barry0501** [comment]
![Simulator Screen Shot - iPhone 11 - 2021-06-27 at 10 05 50](https://user-images.githubusercontent.com/34902237/123531506-52f2a300-d72f-11eb-910f-61935d1ac342.png)

Sorry for my bad English. What I want is after the user selects the name, it is appended after "@".

**Comment by tneotia** [comment]
It should append automatically when selected, does it not append?

**Comment by Barry0501** [comment]
It doesn't. I ran your example project and I found it is not working

**Comment by tneotia** [comment]
Okay then it is a bug. I don't know of a way to get the cursor position, maybe you can run some JS in the `onSelect` callback to append? But I will try to fix this soon, thanks for the report.

**Comment by Barry0501** [comment]
Thank you for your time. Hope you fix it soon, thanks a lot <3

**Comment by tneotia** [comment]
@Barry0501 fixed the issue... dumb mistake on my part. Sorry for the inconvenience. You can use either `master` branch or wait for new release, but a new release may not happen for a few days.
