### ISSUE TITLE
I am not able to understand this which data I have to post to backend API.?

### ISSUE THREAD

**Issue by marslannasr7koncepts** [tneotia/html-editor-enhanced#79]
`var txt = await controller.getText();
                        if (txt.contains('src=\"data:')) {
                          txt =
                              '<text removed due to base-64 data, displaying the text could cause the app to crash>';
                        }
                        setState(() {
                          result = txt;
                        });`
                        
Adding a check if it contain 'src=\data' so it's showing me a text that we are adding but we have to send a data to api then we have to direct pass a result instead of this check   if (txt.contains('src=\"data:')) { }

**Comment by tneotia** [comment]
So in the example I check for `"data:"` in the text string because that means the user has input a base64 image in the editor. This means the string is very very long and displaying it with a `Text` widget causes the app to crash. When uploading to api you should not check this and just upload the entire string.

So in your api call use `String text = await controller.getText();` and simply upload the `text` variable into your api call.

**Comment by tneotia** [comment]
Closing for now if you have any other questions feel free to ask.
